namespace InkPrinterCode.Model
{
    /// <summary>
    /// [2026-09-10] Result of one import -- returned by the BLL to the UI layer for dialog display and log summary
    ///
    /// [Why the counters are split so finely] After an import a dialog must report "how many rows in total, how many
    ///   inserted, how many duplicates, how many invalid"; when abnormal data appears it must further explain
    ///   "whether the duplicates were within the file or already in the DB" and "whether the invalid rows were empty
    ///   rows or contained Chinese". So each sub-count has its own field, and the UI decides which ones to display.
    ///
    /// [Counter identities] TotalRows = ValidCount + DuplicateCount + InvalidCount
    ///   DuplicateCount = FileDuplicateCount + DbDuplicateCount
    ///   InvalidCount   = EmptyRowCount + ChineseRowCount
    ///
    /// [Three finishing states]
    ///   Success=true, Canceled=false  -> completed normally (counts as complete even when ValidCount=0)
    ///   Success=false, Canceled=true  -> the user clicked cancel; the transaction was rolled back and nothing was inserted
    ///   Success=false, Canceled=false -> failed with an error; Message carries a friendly error text and the transaction was rolled back
    /// </summary>
    public class ImportResult
    {
        /// <summary>Whether it completed successfully</summary>
        public bool Success { get; set; } = false;

        /// <summary>Whether the user cancelled it (after cancellation the transaction is rolled back and no data is inserted)</summary>
        public bool Canceled { get; set; } = false;

        /// <summary>Result explanation / failure reason (user-facing friendly text, no stack trace)</summary>
        public string Message { get; set; } = string.Empty;

        /// <summary>Batch Id generated by this import; 0 means not even the batch ledger was written</summary>
        public long BatchId { get; set; } = 0;

        /// <summary>Batch number generated by this import</summary>
        public string BatchNo { get; set; } = string.Empty;

        /// <summary>Total number of rows in the source file</summary>
        public int TotalRows { get; set; } = 0;

        /// <summary>Number of rows actually inserted</summary>
        public int ValidCount { get; set; } = 0;

        /// <summary>Total duplicates = duplicates within the file + already present in the DB</summary>
        public int DuplicateCount { get; set; } = 0;

        /// <summary>Number of rows duplicated within the file itself (the same code appears several times; only the first is kept)</summary>
        public int FileDuplicateCount { get; set; } = 0;

        /// <summary>Number of rows already present in the DB (counted as duplicates across batches and files)</summary>
        public int DbDuplicateCount { get; set; } = 0;

        /// <summary>Total invalid = empty rows + rows containing Chinese</summary>
        public int InvalidCount { get; set; } = 0;

        /// <summary>Number of empty rows (empty after Trim)</summary>
        public int EmptyRowCount { get; set; } = 0;

        /// <summary>Number of rows ignored for containing Chinese characters</summary>
        public int ChineseRowCount { get; set; } = 0;

        /// <summary>Duration of this import (milliseconds)</summary>
        public long ElapsedMs { get; set; } = 0;
    }
}
